name: westdaat

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: DevP@ssw0rd!
    ports:
      - 1433:1433
  sb-emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      # If the config file changes you'll need to recreate the container
      - "./sb-emulator.config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: mssql
      MSSQL_SA_PASSWORD: DevP@ssw0rd!
      ACCEPT_EULA: "Y"
  azurite:
    container_name: azurite
    restart: no
    image: mcr.microsoft.com/azure-storage/azurite:3.34.0
    command: "azurite --blobHost 0.0.0.0 --loose"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    healthcheck:
      test: nc 127.0.0.1 10000 -z
      interval: 1s
      retries: 30
  azurite-init:
    image: mcr.microsoft.com/azure-cli:latest
    container_name: azurite-init
    command:
      - /bin/sh
      - -c
      - |
        az storage container create --name application-documents
        az storage cors add --origins '*' --services 'b' --methods GET POST PUT OPTIONS HEAD --allowed-headers '*'
    depends_on:
      azurite:
        condition: service_healthy
    environment:
      # https://github.com/Azure/Azurite/blob/main/README.md#usage-with-azure-storage-sdks-or-tools
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
