version: "3.3"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: DevP@ssw0rd!
    ports:
      - 1433:1433