trigger:
  branches:
    include: 
    - develop
  paths:
    include: 
    - BackendServices

pool:
  vmImage: 'windows-latest'

steps:
  - task: UseDotNet@2
    inputs:
      version: "6.0.x"
      packageType: sdk
    displayName: "Use .NET 6.0.x"

  - task: DotNetCoreCLI@2
    displayName: "Publish DbUp"
    inputs:
      command: publish
      publishWebProjects: false
      workingDirectory: "$(System.DefaultWorkingDirectory)/BackendServices/OWCA.YOURPROJECT.DbUp"
      arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/DbUp/Application"
      zipAfterPublish: false

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: "SonarCloud Backend"
      organization: "dplref"
      scannerMode: "MSBuild"
      projectKey: "dontpaniclabs_YOURPROJECT_Backend"
      projectName: "YOURPROJECT Backend"

  - task: DotNetCoreCLI@2
    displayName: "Publish Web Client"
    inputs:
      command: publish
      publishWebProjects: false
      workingDirectory: "$(System.DefaultWorkingDirectory)/BackendServices/OWCA.YOURPROJECT.Client.Web"
      arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/Backend/Application"
      zipAfterPublish: false

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: "300"

  - task: PublishBuildArtifacts@1
    displayName: "Publish .NET Artifacts"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "stage_dotnet_drop"
      publishLocation: "Container"
