CREATE TABLE UserProfiles
(
    Id        UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_UserProfiles_Id    PRIMARY KEY NONCLUSTERED DEFAULT NEWID(),
    UserId    UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_UserProfiles_Users FOREIGN KEY REFERENCES Users (Id),
    FirstName NVARCHAR(255)    NOT NULL,
    LastName  NVARCHAR(255)    NOT NULL
);

CREATE INDEX IX_UserProfiles_UserId ON UserProfiles(UserId);