ALTER TABLE dbo.WaterConservationApplicationSubmissions ADD
	AgentFirstName NVARCHAR(100) NOT NULL,
	AgentLastName NVARCHAR(100) NOT NULL,
	AgentEmail NVARCHAR(255) NOT NULL,
	AgentPhoneNumber NVARCHAR(50) NOT NULL,
	LandownerFirstName NVARCHAR(100) NOT NULL,
	LandownerLastName NVARCHAR(100) NOT NULL,
	LandownerEmail NVARCHAR(255) NOT NULL,
	LandownerPhoneNumber NVARCHAR(50) NOT NULL,
	LandownerAddress NVARCHAR(255) NOT NULL,
	LandownerCity NVARCHAR(100) NOT NULL,
	LandownerState NVARCHAR(2) NOT NULL,
	LandownerZipCode NVARCHAR(10) NOT NULL,
	CanalOrIrrigationEntityName NVARCHAR(255) NOT NULL,
	CanalOrIrrigationEntityEmail NVARCHAR(255) NOT NULL,
	CanalOrIrrigationEntityPhoneNumber NVARCHAR(50) NOT NULL,
	ConservationPlanFundingRequestDollarAmount INT NOT NULL,
	ConservationPlanFundingRequestCompensationRateUnits INT NOT NULL,
	ConservationPlanDescription NVARCHAR(4000) NOT NULL,
	ConservationPlanAdditionalInfo NVARCHAR(4000) NULL,
	EstimationSupplementaryDetails NVARCHAR(4000) NULL,
	ProjectLocation NVARCHAR(255) NOT NULL,
	PropertyAdditionalDetails NVARCHAR(4000) NOT NULL,
	DiversionPoint NVARCHAR(255) NOT NULL,
	DiversionPointDetails NVARCHAR(4000) NOT NULL,
	PermitNumber NVARCHAR(255) NOT NULL,
	FacilityDitchName NVARCHAR(255) NOT NULL,
	PriorityDate DATE NOT NULL,
	CertificateNumber NVARCHAR(255) NOT NULL,
	ShareNumber NVARCHAR(255) NOT NULL,
	WaterUseDescription NVARCHAR(4000) NOT NULL;
go
