name: Deploy Prod

on:
  workflow_dispatch:
jobs:
  deploy-infrastructure:
    uses: ./.github/workflows/deploy-infrastructure.yml
    with:
      azure-resource-group: WestDAAT_Prod
      azure-bicep-params-file: azuredeploy.prod.json
    secrets:
      azure-cli-credentials: ${{ secrets.AZURE_AZ_CLI_CREDENTIALS_PROD }}
  deploy-backend:
    uses: ./.github/workflows/deploy-backend.yml
    with:
      azure-resource-group: WestDAAT_Prod
      azure-functionapp-name: westdaat-prod
      azure-apim-name: westdaatprod
      azure-api-name: westdaat-fn-api-prod
      azure-api-url: https://westdaat.azurewebsites.net/api
      azure-auth-tenant-name: westdaat
      azure-auth-audience: 10beb81f-fdfd-43f3-91fd-bb463e331d41 # App Registration ID
      azure-cors-domain: https://westdaat.westernstateswater.org
      database-server-name: westdaat-prod
      database-connection-string: Server=tcp:westdaat-prod.database.windows.net,1433;Initial Catalog=WestDAAT;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication="Active Directory Default";
    secrets:
      azure-cli-credentials: ${{ secrets.AZURE_AZ_CLI_CREDENTIALS_PROD }}
      azure-function-publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE_PROD }}
  deploy-frontend:
    uses: ./.github/workflows/deploy-frontend.yml
    needs: deploy-backend
    with:
      azure-resource-group: WestDAAT_Prod
      azure-storage-account-name: westdaatprod
      azure-cdn-endpoint-name: westdaatprod
      azure-cdn-profile-name: westdaatprod
      react-app-auth-redirect-url: https://westdaat.westernstateswater.org/authredirect.html
      react-app-webapi-url: https://westdaatprod.azure-api.net/api/
      react-app-auth-client-id: 10beb81f-fdfd-43f3-91fd-bb463e331d41
      react-app-auth-authority: https://westdaat.b2clogin.com/westdaat.onmicrosoft.com/b2c_1_signupsignin
      react-app-auth-authority-forgot-password: https://westdaat.b2clogin.com/westdaat.onmicrosoft.com/b2c_1_passwordreset
      react-app-auth-known-authority: https://westdaat.b2clogin.com/westdaat.onmicrosoft.com
      react-app-ga-id: G-GENEQGNY1Q
      react-app-feature-conservation-estimation-tool: disabled
      react-app-water-rights-vector-tile-url: https://api.maptiler.com/tiles/a190c617-ed1a-47fd-81fa-c4b923d40c32/tiles.json?key=8QhUrRdYizgLYetLDiy7
      react-app-overlay-vector-tile-url: https://api.maptiler.com/tiles/80e72552-5c97-43f7-8116-99ef175bb6c1/tiles.json?key=8QhUrRdYizgLYetLDiy7
      react-app-time-series-vector-tile-url: https://api.maptiler.com/tiles/022512af-0ba3-4b82-944a-cadc9db77772/tiles.json?key=8QhUrRdYizgLYetLDiy7
    secrets:
      azure-cli-credentials: ${{ secrets.AZURE_AZ_CLI_CREDENTIALS_PROD }}
