name: Deploy QA

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  FUNCTION_APP_DIR: "src/API/WesternStatesWater.WestDaat.Client.Functions"
  REACT_APP_WEBAPI_URL: "https://westdaat-qa.azurewebsites.net/api/"
  REACT_APP_AUTH_REDIRECT_URL: "https://westdaatqa.westernstateswater.org/authredirect.html" # the URL used by Azure B2C to redirect to your app after login
  REACT_APP_AUTH_CLIENT_ID: "ab3cf308-8a7e-404e-977c-d0227f4a48c4"
  REACT_APP_AUTH_AUTHORITY: "https://westdaatqa.b2clogin.com/westdaatqa.onmicrosoft.com/b2c_1_signupsignin"
  REACT_APP_AUTH_KNOWN_AUTHORITY: "https://westdaatqa.b2clogin.com/westdaatqa.onmicrosoft.com"
  REACT_APP_GA_ID: "G-KFL0TGM4B8" # set the Google Analytics measurement ID
  AZURE_RESOURCE_GROUP: WestDAAT_QA # set the resource group name
  AZURE_FUNCTIONAPP_NAME: westdaat-qa # set this to the name of your Azure Web App
  AZURE_STORAGE_ACCOUNT_NAME: westdaatqa # set the storage account of static site
  AZURE_CDN_ENDPOINT_NAME: westdaatqa # set the storage account of static site
  AZURE_CDN_PROFILE_NAME: westdaatqa # set the cdn profile name

jobs:
  deploy-backend:
    uses: ./.github/workflows/deploy-backend.yml
    with:
      azure-resource-group: WestDAAT_QA
      azure-functionapp-name: westdaat-qa
      azure-apim-name: westdaatqa
      azure-api-name: westdaat-fn-api-qa
      azure-api-url: https://westdaatqa.azure-api.net/api
    secrets:
      azure-cli-credentials: ${{ secrets.AZURE_AZ_CLI_CREDENTIALS_QA }}
      azure-function-publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE_QA }}
  deploy-frontend:
    uses: ./.github/workflows/deploy-frontend.yml
    needs: deploy-backend
    with:
      azure-resource-group: WestDAAT_QA
      azure-functionapp-name: westdaat-qa
      azure-apim-name: westdaatqa
      azure-api-name: westdaat-fn-api-qa
      azure-api-url: https://westdaatqa.azure-api.net/api
    secrets:
      azure-cli-credentials: ${{ secrets.AZURE_AZ_CLI_CREDENTIALS_QA }}
      azure-function-publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE_QA }}
