name: Deploy QA

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy-backend:
    uses: ./.github/workflows/deploy-backend.yml
    with:
      azure-resource-group: WestDAAT_QA
      azure-functionapp-name: westdaat-qa
      azure-apim-name: westdaatqa
      azure-api-name: westdaat-fn-api-qa
      azure-api-url: https://westdaatqa.azure-api.net/api
    secrets:
      azure-cli-credentials: ${{ secrets.AZURE_AZ_CLI_CREDENTIALS_QA }}
      azure-function-publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE_QA }}
  deploy-frontend:
    uses: ./.github/workflows/deploy-frontend.yml
    needs: deploy-backend
    with:
      azure-resource-group: WestDAAT_QA
      azure-storage-account-name: westdaatqa
      azure-cdn-endpoint-name: westdaatqa
      azure-cdn-profile-name: westdaatqa
    secrets:
      azure-cli-credentials: ${{ secrets.AZURE_AZ_CLI_CREDENTIALS_QA }}
