name: PR Backend

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/API

    steps:
      - uses: actions/checkout@v2
      - name: Start Docker Containers
        run: docker compose -f ci-compose.yml up -d
        working-directory: .github
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: .NET Build
        run: dotnet build --no-restore
      - name: Create Database
        run: docker exec -i mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P 'DevP@ssw0rd!' -Q 'create database WaDE2'
      - name: Check out WaDE2.0
        uses: actions/checkout@v2
        with:
          repository: WSWCWaterDataExchange/WaDE2.0
          ref: develop
      - name: DbUp WaDE2.0
        run: dotnet run --args "Server=localhost; Initial Catalog=WaDE2; User=sa; Password=DevP@ssw0rd!;"
        working-directory: source/WesternStatesWater.WaDE.DbUp
      - name: Check out WestDaat
        uses: actions/checkout@v2
        with:
          repository: WSWCWaterDataExchange/WestDaat
          ref: develop
      - name: DbUp WestDaat
        run: dotnet run --args "Server=localhost; Initial Catalog=WestDAAT; User=sa; Password=DevP@ssw0rd!;"
        working-directory: src/WesternStatesWater.WestDaat.DbUp
      - uses: actions/checkout@v2
      - name: .NET Test
        run: dotnet test
        env:
          Database__WadeConnectionString: "Server=localhost; Initial Catalog=WaDE2; User=sa; Password=DevP@ssw0rd!; MultipleActiveResultSets=False;TrustServerCertificate=true;"
          Database__WestDaatConnectionString: "Server=localhost; Initial Catalog=WestDAAT; User=sa; Password=DevP@ssw0rd!; MultipleActiveResultSets=False;TrustServerCertificate=true;"
        working-directory: src/API
