name: PR Backend

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]


jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/API

    steps:
    - uses: actions/checkout@v2
    - name: Create Database Container
      run: docker-compose -f ci-compose.yml up -d
      working-directory: .github
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: .NET Build
      run: dotnet build --no-restore
    - name: Create Database
      run: docker exec -i mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'DevP@ssw0rd!' -Q 'create database WaDE'
    - name: DbUp
      run: dotnet run
      working-directory: src/API/WesternStatesWater.WaDE.DbUp
    - name: .NET Test
      run: dotnet test --no-build --verbosity normal
