name: PR Backend

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/API

    steps:
      - uses: actions/checkout@v2
      - name: Start Docker Containers
        run: docker compose -f ci-compose.yml up -d
        working-directory: .github
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: .NET Build
        run: dotnet build --no-restore
      - name: Create Database
        run: docker exec -i mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P 'DevP@ssw0rd!' -Q 'create database WaDE2'
      # - name: Check out WaDE2.0
      #   uses: actions/checkout@v2
      #   with:
      #     repository: WSWCWaterDataExchange/WaDE2.0
      #     ref: develop
      # - name: DbUp
      #   run: dotnet run --args "Server=localhost; Initial Catalog=WaDE2; User=sa; Password=DevP@ssw0rd!;"
      #   working-directory: source/WesternStatesWater.WaDE.DbUp
      # - uses: actions/checkout@v2
      # - name: .NET Test
      #   run: dotnet test
      #   env:
      #     Database__ConnectionString: "Server=localhost; Initial Catalog=WaDE2; User=sa; Password=DevP@ssw0rd!; MultipleActiveResultSets=False;TrustServerCertificate=true;"
      #   working-directory: src/API


      # Test OpenAPI document generation. Will move to on-merge-*.yml when ready.
      - name: Install Azure Functions Core Tools
        run: sudo apt-get install -y azure-functions-core-tools-4

      - name: Update OpenAPI Script Permissions
        run: chmod 777 ./get-openapi-document.sh
        working-directory: .github/workflows

      - name: Generate OpenAPI document
        id: oai
        run: ./get-openapi-document.sh -d 45 -p "src/API/WesternStatesWater.WestDaat.Client.Functions" -o ".github/workflows"
        working-directory: .github/workflows

      - name: Check generated OpenAPI document
        shell: pwsh
        run: |
          echo "Generated Document:"
          $json = Get-Content -Path ./swagger.json | ConvertFrom-Json
          $result = $json.openapi -eq "3.0.1"
          echo "Check result: $result"
        working-directory: .github/workflows
